### ISSUE TITLE
Support CancellationTokens

### ISSUE THREAD

**Issue by dashkan** [pmorelli92/SoapHttpClient#11]
@pmorelli92 ,

Thanks for the great library. I added support for cancellation tokens in a PR #10 . Can you take a look to see if it's something you are willing to add to the project?

Thanks!

**Comment by pmorelli92** [comment]
Hi @dashkan, thanks for the contribution. I just merged, going to upload the package to nuget some day today or at most tomorrow!

Regards

**Comment by pmorelli92** [comment]
You can find the new package on nuget.
