### ISSUE TITLE
would U consider to support CDATA in body?

### ISSUE THREAD

**Issue by nkdanfer** [pmorelli92/SoapHttpClient#16]
I've some reason to send a CDATA data, but don't known how to do it.
If it's not an issue, please let me known the solution. Thx.

**Comment by pmorelli92** [comment]
Maybe you want to do [this](https://stackoverflow.com/a/9531777).
Feel free to reopen if this does not solve your issue.

**Comment by nkdanfer** [comment]
thx. I was mixed this with an other project not using SoapHttpClient. Your work's good. Well done.
