### ISSUE TITLE
How to specify method name?

### ISSUE THREAD

**Issue by dehghani-mehdi** [pmorelli92/SoapHttpClient#17]
Hi,

I want to call web service which expect following:

```
POST ... HTTP/1.1
Host: ...
Content-Type: text/xml; charset=utf-8
Content-Length: length
SOAPAction: "..."

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope ...>
  <soap:Body>
    <METHOD_NAME xmlns="...">
      <requestData />
    </METHOD_NAME >
  </soap:Body>
</soap:Envelope>
```

How to tell `SoapHttpClient` about `METHOD_NAME`?

**Comment by pmorelli92** [comment]
This library is expecting an XML which will end up being wrapped inside the `<soap:Body>` so that functionality you want to achieve is doable with XElement:

```
var body = new XElement("methodName", new XElement("requestData"));
Console.Write(body);
```

**Comment by dehghani-mehdi** [comment]
@pmorelli92 what about that `xmlns` attribute for `METHOD_NAME ` tag?
```
    XNamespace xNamespace = "http://tempuri.org/";
    var method = new XElement(xNamespace + methodName, bodies);
```
Output:
```
    <MethodName xmlns="http://tempuri.org/">
        <ParamName xmlns="">...</ParamName>
    </MethodName>
```

How can I get rid of `xmlns=""`? I can not test the web service (which I'm working with) easily, so I need to make sure everything is correct. any idea on this?
