### ISSUE TITLE
How to add the below sample one in the body using this api

### ISSUE THREAD

**Issue by gnaneswarreddy** [pmorelli92/SoapHttpClient#18]
<tem:GetByStatusAndId>
         
         <tem:distributorId>
            
            <arr:guid>bee3c0be-ccbf-4882-ad5a-d288f5677a51</arr:guid>
         </tem:distributorId>
         
         <tem:distributorStatus>
            
            <arr:unsignedByte>123</arr:unsignedByte>
         </tem:distributorStatus>
      </tem:GetByStatusAndId>

**Comment by gnaneswarreddy** [comment]
I have to send two or three parameters like guid, unsigned byte, username, password elements in the body how to do that

**Comment by pmorelli92** [comment]
Hi @gnaneswarreddy this library sends an XML payload using the SOAP protocol, there by I am not answering support on how to create the desired XML; for that you will be good following the documentation linked here: 

https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xelement?view=netframework-4.8

**Comment by gnaneswarreddy** [comment]
Hi Thankyou i was able to fix it.
But how to get the response through API as i have to validate the results with the value i will be returned like we enter username and password and it returns "Successfull".
I am not seeing that in the example. Could you please help.
