### ISSUE TITLE
how to setup authorization?

### ISSUE THREAD

**Issue by lvshiwei** [pmorelli92/SoapHttpClient#20]
Foundational http request message below:

> Http 1.1
> 
> ...headers...
> 
> **Authorization**: Basic [Base64 encoded with user name : password...]
> 

In this situation, how to setup "**Authorization**" header by SoapHttpClient?

thank you very much

**Comment by pmorelli92** [comment]
Hi @lvshiwei ! Sorry for the delay on this.

The SoapHttpClient is just a wrapper of the HttpClient. 
So when you instantiate the SoapHttpClient you can customise the underlying HttpClient to add the header you need :)
