### ISSUE TITLE
Release of latest version of the soap client

### ISSUE THREAD

**Issue by kanterukb** [pmorelli92/SoapHttpClient#6]
Hi @pmorelli92 
Is it possible to push latest version of SoapHttpClient to nuget?
thanks

**Comment by pmorelli92** [comment]
Hi @kanterukb, I am finishing a refactor, I guess I will upload version 2.0 in the next few days.

**Comment by kanterukb** [comment]
thank you!

**Comment by pmorelli92** [comment]
@kanterukb I already uploaded the 2.0.0 version, it should be visible soon. Regards!
