### ISSUE TITLE
Header should be SOAPAction for Soap 1.1 instead of ActionHeader

### ISSUE THREAD

**Issue by epgremill3** [pmorelli92/SoapHttpClient#8]
I'm using the SoapClient to communicate with a SOAP 1.1 service. I got an error that the action wasn't defined even though I specified an action when I called to post async. I discovered this is because the HTTP Request Header that the SoapClient sets is "ActionHeader" but I believe the SOAP 1.1 specification requires a "SOAPAction" header (https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528).

Any chance you can change line 80 of SoapClient.cs to use "SOAPAction" instead of "ActionHeader"?

**Comment by pmorelli92** [comment]
@epgremill3 done! Sorry for the delay.
